version: "3"
services:
  minify-ts:
    image: dev-node
    build:
      cache_from:
        - dev-node
      context: ../dev-node
      args:
        NODE_VERSION: 16
    environment:
      - PROJECT_PATH=minify-ts
      - INIT_FILE=init.sh
      - WAIT_SEC=2
      - TZ=
    volumes:
      - type: bind
        source: ${GIT_CONFIG_PATH:-~/.gitconfig}
        target: /home/user/.gitconfig
        read_only: true
      - type: bind
        source: ${SSH_PATH:-~/.ssh}
        target: /home/user/.ssh
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /home/user/.bash_aliases
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /root/.bash_aliases
        read_only: true
      - home:/home/user:delegated
      - ../..:/opt/workspace/minify-ts
volumes:
  home:
