alias ls='ls --color=auto'
alias l='ls -la'
alias ll='ls -l'
alias grep='grep --color=auto'
PS1='\n\[\e[35m\]--------\n\t \[\e[33m\]\h \[\e[32m\][\w]\n\[\e[35m\]-------- \[\e[33m\]\u\[\e[32m\]\$ \[\e[m\]'
